<?php

return [
    'pushbullet.access_token' => '',
    'app.key'                 => 'YourSecretKey!!!',
    'app.timezone'            => 'UTC',
    'app.url'                 => 'http://localhost',
    'app.debug'               => false,
    'app.db.type'             => 'mysql',
    'app.db.host'             => '',
    'app.db.database'         => '',
    'app.db.username'         => '',
    'app.db.password'         => '',
    'app.db.prefix'           => '',
    'app.email.driver'        => '',
    'app.email.host'          => '',
    'app.email.port'          => '',
    'app.email.from'          => [
        'address' => 'team@ekosme.me',
        'name'    => 'Zespół ekosme.me',
    ],
    'app.email.encryption' => 'tls',
    'app.email.username'   => '',
    'app.email.password'   => '',
    'app.email.pretend'    => false,
    'app.queue.driver'     => '',
    'app.queue.host'       => '',
    'app.queue.queue'      => 'default',
    'app.queue.ttr'        => '',
    'lock.username'        => 'test',
    'lock.password'        => 'test',
    'dropbox.key'          => '',
    'dropbox.secret'       => '',
    'dropbox.token'        => '',
    'dropbox.app'          => '',
    'dropbox.folder'       => 'ekosmeme',
    'rollbar.token'        => '',
];
